In [ ]:
##Fake News Classifier ##LSTM

import pandas as pd

df = pd.read_csv('/content/train1.csv', error_bad_lines=False, engine='python')

<ipython-input-9-da4ceae7f06b>:5: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv('/content/train1.csv', error_bad_lines=False, engine='python')
Skipping line 12056: unexpected end of data


In [ ]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [ ]:
df.isnull().sum()

id           0
title      327
author    1122
text        25
label        0
dtype: int64

In [ ]:
#Drop Nan Values
df = df.dropna()

In [ ]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [ ]:
# Independent feature
X = df.drop('label',axis=1)

In [ ]:
#Dependent feature
y=df['label']

In [ ]:
X.shape

(10605, 4)

In [ ]:
y.shape

(10605,)

In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.12.0'

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
voc_size = 5000

In [ ]:

messages = X.copy()

In [ ]:
messages['title'][0]

'House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It'

In [ ]:
messages

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
12045  12045  Steele: Elon Musk Doesn’t Want Government Subs...   
12047  12047          YouTube censoring videos – on censorship!   
12048  12048  Prime Minster John Key caught channeling milli...   
12051  12051  Why Does the Beauty Industry Ignore Curvy Mode...   
12052  12052  Mike Dubke Resigns as White House Communicatio...   

                                 author  \
0                         Darrell Lucus   
1                       Daniel J. Flynn   
2                    Consortiumnews.com   
3                       Jessica Purkiss   
4                        Howard Portnoy   
...                                 ...   
12045                 Michael S. Steele   
12047                     Don Wrightman   
12048  tokyowashi (noreply@blogger.com)   
12051                    Crystal Martin   
12052                  Charlie Spiering   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
12045  Republicans have found healthcare reform to be...  
12047  YouTube censoring videos – on censorship! shar...  
12048  Source: Seemorerocks \n\nNovember 1, 2016 \n\n...  
12051  A photo of Philomena Kwao elicits a guttural “...  
12052  After just three months on the job, White Hous...  

[10605 rows x 4 columns]

In [ ]:
messages.reset_index(inplace=True)

In [ ]:
messages

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
10600  12045  12045  Steele: Elon Musk Doesn’t Want Government Subs...   
10601  12047  12047          YouTube censoring videos – on censorship!   
10602  12048  12048  Prime Minster John Key caught channeling milli...   
10603  12051  12051  Why Does the Beauty Industry Ignore Curvy Mode...   
10604  12052  12052  Mike Dubke Resigns as White House Communicatio...   

                                 author  \
0                         Darrell Lucus   
1                       Daniel J. Flynn   
2                    Consortiumnews.com   
3                       Jessica Purkiss   
4                        Howard Portnoy   
...                                 ...   
10600                 Michael S. Steele   
10601                     Don Wrightman   
10602  tokyowashi (noreply@blogger.com)   
10603                    Crystal Martin   
10604                  Charlie Spiering   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
10600  Republicans have found healthcare reform to be...  
10601  YouTube censoring videos – on censorship! shar...  
10602  Source: Seemorerocks \n\nNovember 1, 2016 \n\n...  
10603  A photo of Philomena Kwao elicits a guttural “...  
10604  After just three months on the job, White Hous...  

[10605 rows x 5 columns]

In [ ]:
import nltk
import re
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
#Data Preprocessing

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

corpus = []

for i in range(0, len(messages)):
  review = re.sub('[^a-zA-Z0-9]', ' ', messages['title'][i])
  review = review.lower()
  review = review.split()

  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

In [ ]:
corpus[0]

'hous dem aid even see comey letter jason chaffetz tweet'

In [ ]:
#One_hot rep:

onehot_rpr = [one_hot(words, voc_size) for words in corpus]
onehot_rpr

[[1950, 2780, 23, 2645, 1799, 2460, 1949, 579, 4968, 4114],
 [354, 1245, 1151, 2946, 3570, 2292, 2116],
 [430, 1080, 559, 3021],
 [356, 4560, 3394, 3795, 586, 3596, 4103],
 [4698, 3570, 367, 4963, 3134, 4673, 3570, 65, 1415, 1509],
 [748,
  3968,
  4904,
  4809,
  2746,
  2078,
  1229,
  3197,
  2965,
  2253,
  4886,
  2377,
  2972,
  3396,
  2116],
 [337, 3012, 3637, 1199, 2018, 26, 56, 568, 1185, 3570, 2369],
 [4758, 1134, 2670, 1717, 3893, 2177, 2078, 341, 1185, 3570, 2369],
 [4633, 925, 4844, 1836, 1512, 3100, 3276, 899, 2078, 3851],
 [3528, 2595, 4663, 1262, 1695, 1797, 1019, 4748],
 [2845, 1184, 1915, 1554, 852, 3875, 240, 165, 552, 4843, 3100],
 [586, 4582, 1799, 3100, 2078, 3893],
 [323, 1659, 817, 4864, 1722, 3804, 1846, 2563, 185],
 [2200, 1389, 1972, 3467, 1157, 3196, 3505, 1185, 3570, 2369],
 [647, 3926, 3221, 2178, 2849, 1185, 3570, 2369],
 [1467, 1315, 4171, 4943, 735, 4365, 2138, 2279, 4887, 302, 4484, 209],
 [2786, 3641, 1245],
 [2358, 4017, 3080, 1183, 2078, 1988, 1353

In [ ]:
corpus[0]

'hous dem aid even see comey letter jason chaffetz tweet'

In [ ]:
onehot_rpr[0]

[1950, 2780, 23, 2645, 1799, 2460, 1949, 579, 4968, 4114]

In [ ]:
#Embedding Rep: and equal the length of seq with padding

sent_len = 20
embedd = pad_sequences(onehot_rpr, padding='pre', maxlen=sent_len)
print(embedd)

[[   0    0    0 ...  579 4968 4114]
 [   0    0    0 ... 3570 2292 2116]
 [   0    0    0 ... 1080  559 3021]
 ...
 [   0    0    0 ... 4079 1151 4194]
 [   0    0    0 ... 1185 3570 2369]
 [   0    0    0 ... 1950 2615  243]]


In [ ]:
from keras.utils.sidecar_evaluator import optimizer
from tensorflow.keras.layers import Dropout
# Creating model

embedd_vec_feat = 40
model = Sequential()
model.add(Embedding(voc_size, embedd_vec_feat, input_length=sent_len))
model.add(Dropout(0.33))
model.add(LSTM(100))
model.add(Dropout(0.33))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 20, 40)            200000    
                                                                 
 dropout (Dropout)           (None, 20, 40)            0         
                                                                 
 lstm_1 (LSTM)               (None, 100)               56400     
                                                                 
 dropout_1 (Dropout)         (None, 100)               0         
                                                                 
 dense_1 (Dense)             (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
len(embedd), y.shape

(10605, (10605,))

In [ ]:
import numpy as np

X_final = np.array(embedd)
y_final = np.array(y)

In [ ]:

y_final

array([1, 0, 1, ..., 1, 0, 0])

In [ ]:
X_final.shape, y_final.shape

((10605, 20), (10605,))

In [ ]:
#Train Test split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [ ]:
#Model Training

model.fit(X_train, y_train, validation_data=(X_test,y_test), epochs=10, batch_size=128)

Epoch 1/10
56/56 [==============================] - 11s 147ms/step - loss: 0.5708 - accuracy: 0.7040 - val_loss: 0.3653 - val_accuracy: 0.8234
Epoch 2/10
56/56 [==============================] - 5s 91ms/step - loss: 0.2420 - accuracy: 0.9011 - val_loss: 0.2141 - val_accuracy: 0.9086
Epoch 3/10
56/56 [==============================] - 2s 40ms/step - loss: 0.1450 - accuracy: 0.9488 - val_loss: 0.1935 - val_accuracy: 0.9197
Epoch 4/10
56/56 [==============================] - 1s 25ms/step - loss: 0.0986 - accuracy: 0.9671 - val_loss: 0.2092 - val_accuracy: 0.9166
Epoch 5/10
56/56 [==============================] - 1s 26ms/step - loss: 0.0712 - accuracy: 0.9775 - val_loss: 0.2605 - val_accuracy: 0.9231
Epoch 6/10
56/56 [==============================] - 2s 28ms/step - loss: 0.0528 - accuracy: 0.9845 - val_loss: 0.2895 - val_accuracy: 0.9171
Epoch 7/10
56/56 [==============================] - 2s 30ms/step - loss: 0.0427 - accuracy: 0.9869 - val_loss: 0.2943 - val_accuracy: 0.9137
Epoch 8/10


In [ ]:
y_pred = model.predict(X_test)

110/110 [==============================] - 1s 3ms/step


In [ ]:
y_pred = np.where(y_pred> 0.5, 1,0)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [ ]:
confusion_matrix(y_test, y_pred)

array([[1847,  144],
       [ 178, 1331]])

In [ ]:
accuracy_score(y_test, y_pred)

0.908

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.91      0.93      0.92      1991
           1       0.90      0.88      0.89      1509

    accuracy                           0.91      3500
   macro avg       0.91      0.90      0.91      3500
weighted avg       0.91      0.91      0.91      3500

